"""
Signals service — reads from repository (Redis → DB → seed).
Thin layer: filtering, pagination, audit trail generation.
"""
import math
import statistics
from typing import Optional
from app.data.repository import repository


def _enrich(signal: dict, idx: int) -> dict:
    """Ensure all expected fields exist with sensible defaults."""
    s = dict(signal)
    s.setdefault("age_minutes", idx * 8 + 3)
    s.setdefault("impact_score", max(1, min(10, int(s.get("confidence", 0.7) * 10))))
    s.setdefault("z_score", s.get("anomaly_score", 0))
    s.setdefault("anomaly_score", s.get("z_score", 0))
    s.setdefault("reward_risk_ratio", 2.0)
    s.setdefault("historical_win_rate", s.get("backtest", {}).get("win_rate", 0.62))
    s.setdefault("avg_30d_return", s.get("backtest", {}).get("avg_30d_return", 0.05))
    s.setdefault("portfolio_impact_pct", 0.0)
    s.setdefault("sources", [])
    s.setdefault("reasoning_steps", [])
    s.setdefault("watch_items", [])
    s.setdefault("tags", [])
    return s


async def list_signals(
    sector: str = "",
    signal_type: str = "",
    min_confidence: float = 0.0,
    limit: int = 20,
    offset: int = 0,
) -> list[dict]:
    raw = await repository.get_signals()
    signals = [_enrich(s, i) for i, s in enumerate(raw)]
    # Filter
    if sector:
        signals = [s for s in signals if sector.lower() in s.get("sector", "").lower()]
    if signal_type:
        signals = [s for s in signals if signal_type.lower() in s.get("signal_type", "").lower()]
    if min_confidence:
        signals = [s for s in signals if s.get("confidence", 0) >= min_confidence]
    # Sort: impact_score × confidence × |z_score|
    signals.sort(key=lambda s: s["impact_score"] * s.get("confidence", 0.7) * (1 + abs(s.get("z_score", 0))), reverse=True)
    return signals[offset : offset + limit]


async def count_signals(**kwargs) -> int:
    results = await list_signals(**{k: v for k, v in kwargs.items() if k not in ("limit", "offset")}, limit=1000)
    return len(results)


async def get_signal(signal_id: str) -> dict | None:
    signals = await repository.get_signals()
    for s in signals:
        if s.get("id") == signal_id:
            return _enrich(s, 0)
    return None


async def get_high_confidence_signals(threshold: float = 0.78) -> list[dict]:
    return await list_signals(min_confidence=threshold, limit=10)


async def get_signals_by_sector(sector: str) -> list[dict]:
    return await list_signals(sector=sector, limit=15)


async def get_audit_trail(signal_id: str) -> dict | None:
    signal = await get_signal(signal_id)
    if not signal:
        return None
    z = signal.get("z_score", 0)
    conf = signal.get("confidence", 0.7)
    return {
        "signal_id": signal_id,
        "ticker": signal["ticker"],
        "event_timestamp": signal.get("updated_at", ""),
        "input_snapshot": {
            "sources": signal.get("sources", []),
            "sector": signal.get("sector", ""),
            "age_minutes": signal.get("age_minutes", 0),
        },
        "enrichment_snapshot": {
            "z_score": z,
            "anomaly_score": signal.get("anomaly_score", abs(z)),
            "volume_ratio": round(1.0 + abs(z) * 0.3, 2),
            "rsi_estimate": round(50 + z * 8, 1),
            "tags": signal.get("tags", []),
        },
        "reasoning_chain": signal.get("reasoning_steps", []),
        "output": {
            "headline": signal.get("headline", ""),
            "summary": signal.get("summary", ""),
            "watch_items": signal.get("watch_items", []),
        },
        "confidence_metadata": {
            "base_confidence": round(conf - 0.05, 3),
            "z_score_boost": round(min(0.15, abs(z) * 0.04), 3),
            "final_confidence": conf,
            "data_freshness_minutes": signal.get("age_minutes", 0),
            "failure_contexts": [r for r in signal.get("reasoning_steps", []) if "risk" in r.lower() or "caution" in r.lower()],
        },
        "disclaimer": "This signal is generated by AI from public data sources. Not SEBI-registered investment advice.",
    }
